services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: qwerty123
      MYSQL_DATABASE: my_database
      MYSQL_USER: bobr2
      MYSQL_PASSWORD: qwerty123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webnet
  
  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql+pymysql://bobr2:qwerty123@db/my_database
    ports:
      - "5000:5000"
    networks:
      - webnet
  
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - webnet

volumes:
  db_data:

networks:
  webnet:
    driver: bridge